config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create, :show, :edit, :destroy, :update]
  
  # resources :items do
  #   resource :reviews, :except => :destroy
  #   member do
  #       delete  'reviews'
  #   end
  #   resources :reviews, only: [:destroy]
  #   end
  
  resources :items , shallow: true do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews
  
  #validates :code, presence: true,length: { maximum: 255 }
  #validates :name, presence: true, length: { maximum: 15 }
  #validates :url, presence: true,　length: { maximum: 255 }
  #validates :image_url, presence: true,　length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
  
  validates :user_id, presence: true
  validates :item_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :name, presence: true, length: { maximum: 10 }
  validates :introduction, presence: true, length: { maximum: 100 }
  
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    @items = Item.all.page(params[:page])
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  
  def index
    @item = Item.find(params[:item_id])
    @reviews = @item.reviews.all.page(params[:page])
  end
  
  def new
    @item = Item.find(params[:item_id])
    @review = @item.reviews.new
  end

  def create
    @item = Item.find(params[:item_id])
    @review = @item.reviews.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      flash[:success] = 'レビュー が正常に投稿されました'
      redirect_to item_reviews_path
    else
      flash.now[:danger] = 'レビュー が投稿されませんでした'
      render :new
    end
  end

  def destroy
    @review.destroy
    flash[:success] = 'レビューを削除しました。'
    redirect_back(fallback_location: root_url)
  end

  private
  
  def set_review
    @item = Item.find(params[:item_id])
    @review = @item.reviews.find(params[:id])
  end
  # Strong Parameter
  def review_params
    params.require(:review).permit(:content)
  end
  
  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    unless @review
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_path
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :destroy]
 
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
    render :edit
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      redirect_to @user
      flash[:success] = "プロフィールを更新しました" 
    else
      flash.now[:danger] = 'プロフィールを更新できませんでした。'
      render'edit'
    end
  end
  
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/items/index.html.erb
<h1>商品一覧</h1>

<br /><p>ここには、口コミを書くことのできる商品が用意されています。<br />惣菜は、管理人が用意するので、面倒な手間は必要ありません。</p>

<ul class="media-list">
  <% @items.each do |item| %>
    <div class="row">
      <aside class="col-xs-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <li class="media">
              <div class="clearfix">
              </div>
              <div>
                <%= item.id %> : <%= link_to item.title, item %>
              </div>
              <br />
              <div>
                 <%= item.content %>
              </div>
              <div>
                <%= image_tag(item.image_url,:size =>"200x150") %>
              </div>
            </li>
          </div>
        </div>
      </aside>
    </div>
  <% end %>
  <%= paginate @items %>
</ul>
      

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<div class="row">
  <aside class="col-xs-6">
    <h1><%= @item.title %></h1>
    <img border="0" src="/images/<%= @item.image_url %>" class="sample" width = "480" height = "320">
    <h2>商品情報</h2>
      <p><%= @item.content %></p>
      <%= link_to 'レビューする', new_item_review_path(@item, @review), class: 'btn btn-primary' %>
      <br /><br />
      <%= link_to 'レビュー一覧', item_reviews_path(@item, @review), class: 'btn btn-primary' %>
  </aside>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">トップに戻る</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to items_path do %>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                商品一覧
              <% end %>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'マイページ', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to '新規登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>惣菜レビューのSOUZAI</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/index.html.erb
<ul class="media-list">
  <div>
    <img border="0" src="/images/<%= @item.image_url %>" class="sample" width = "300" height = "225">
  </div>
  <% @reviews.each do |review| %>
    <% user = review.user %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(review.user, options = { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to user.name, user_path(user) %> <span class="text-muted">posted at <%= review.created_at %></span>
        </div>
        <div>
          <p><%= review.content %></p>
        </div>
        <div>
          <% if current_user == review.user %>
            <%= link_to 'このレビューを削除する', review, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger btn-xs' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate @reviews %>
</ul>

app/views/reviews/new.html.erb
<div class="row">
  <aside class="col-xs-6">
    <h1>レビュー投稿</h1>

    <%= form_for ([@item, @review]) do |f| %>
      <%= f.label :content, 'レビュー' %>
      <%= f.text_area :content, class: 'form-control', rows: 5 %>
      <br />
      <%= f.submit '投稿' , class: 'btn btn-success btn-lg'%>
    <% end %>
  </aside>
</div>

app/views/reviews/show.html.erb
<ul class="media-list">
  <% @reviews.each do |review| %>
    <% user = review.user %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(review.user, options = { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to user.name, user_path(user) %> <span class="text-muted">posted at <%= review.created_at %></span>
        </div>
        <div>
          <p><%= review.content %></p>
        </div>
        <div>
          <% if current_user == review.user %>
            <%= link_to 'このメッセージを削除する', @review, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger btn-xs' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1>惣菜レビューのSOUZAIへようこそ</h1>
        <table>
          <tr>
            <td><%= image_tag('/images/humburg.jpg' , :size =>"480x360") %></td>
            <td><%= image_tag('/images/karaage.jpg' , :size =>"480x360") %></td>
          </tr>
        </table>
        <br />
        <p>ここでは、我々が日常口にしている惣菜の口コミを書くことができます。<br />まずは、ページ上部のナビバーにある「商品一覧」へ行きましょう。</p>
      </div>
    </div>
  </div>
<% else %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1>惣菜レビューのSOUZAIへようこそ</h1>
        <table>
          <tr>
            <td><%= image_tag('/images/humburg.jpg' , :size =>"480x360") %></td>
            <td><%= image_tag('/images/karaage.jpg' , :size =>"480x360") %></td>
          </tr>
        </table>
        <br />
        <br />
        <%= link_to '会員登録', signup_path, class: 'btn btn-success btn-lg' %>
        <%= link_to 'ログイン', login_path, class: 'btn btn-success btn-lg' %>
        <p>ここでは、我々が日常口にしている惣菜の口コミを書くことができます。<br />まずはログインをお願いします。会員登録が済んでいない方は、会員登録へ</p>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">ユーザー更新</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="gravatar_edit">
            <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, size: 100) %>" alt="">
            <a href="http://gravatar.com/emails" target="_blank">画像編集</a>
          </div>
          <br />
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :自己紹介 %>
            <%= f.text_area :introduction, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '更新する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>マイページ</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="gravatar_new">
            <a href="http://gravatar.com/emails" target="_blank">画像追加</a>
          </div>
          <br />
          
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :introduction, '自己紹介'  %>
            <%= f.text_area :introduction, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<center>
  <div class="user-profile">
    <div class="icon-text-center">
      <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, size: 100) %>" alt="">
    </div>
    <div class="name text-center">
      <h1><%= @user.name %></h1>
    </div>
    <div>
      <p><%= @user.introduction %></p>
    </div>
  </div>
  <% if @user == current_user %>
    <%= link_to 'ユーザー情報を更新', edit_user_path(current_user), class: 'btn btn-primary' %>
  <% end %>
</center>